### ISSUE TITLE
It can't be automatic.

### ISSUE THREAD

**Issue by Paul-TO** [Bluesforests/Comfyui_LongTextSplit#1]
Thanks for your plugin.
I tried the default workflow and tried to generate 3 different images, but found that it only generated one batch of prompt words at a time, and it would jump to the next batch of prompt words when it was generated again. I tried to change the batch-size to 3, but it generated three images of the same prompt word.
It doesn't seem to be able to automatically generate three batches of prompt words. Is there something wrong with my settings?

**Comment by Bluesforests** [comment]
hey man,  You need to set the batch count instead of the batch size. The batch count is set at the comfyui queue, not in the workflow's batch size.
<img width="385" alt="image" src="https://github.com/user-attachments/assets/af07f4d4-282a-4b5c-9261-714d1c0a298f">

**Comment by Paul-TO** [comment]
Thanks, I found it. Our display is different.
![20241210204718](https://github.com/user-attachments/assets/f4870756-0874-4e44-aebe-c7a4e20eb989)
